In [57]:
import numpy as np

In [ ]:
grades = np.array([
    [85, 90, 78, 92, 88], #stud-1
    [70, 75, 72, 68, 74], #stud-2
    [95, 98, 92, 96, 97], #stud-3
    [60, 65, 58, 62, 59], #stud-4
    [88, 82, 91, 85, 87], #stud-5
    [50, 55, 45, 60, 52]  #stud-6
])
print(grades)

[[85 90 78 92 88]
 [70 75 72 68 74]
 [95 98 92 96 97]
 [60 65 58 62 59]
 [88 82 91 85 87]
 [50 55 45 60 52]]


In [75]:
name = np.array(["Abdullah", "Hossam", "Ramadan", "Amin", "Ibrahim", "Siam"])
print(name)

['Abdullah' 'Hossam' 'Ramadan' 'Amin' 'Ibrahim' 'Siam']


In [59]:
student_avg = grades.mean(axis=1)
print(student_avg)

subject_avg = grades.mean(axis=0)
print(subject_avg)

[86.6 71.8 95.6 60.8 86.6 52.4]
[74.66666667 77.5        72.66666667 77.16666667 76.16666667]


In [60]:
best_stud = np.argmax(student_avg)
worst_stud = np.argmin(student_avg)

print(student_avg[best_stud])
print(student_avg[worst_stud])

95.6
52.4


In [77]:
passed = grades[student_avg > 85]
print(passed)

[[85 90 78 92 88]
 [95 98 92 96 97]
 [88 82 91 85 87]]


In [72]:
stand_div = grades.std(axis=1)
print(s)

[4.88262225 2.56124969 2.05912603 2.48193473 3.00665928 5.0039984 ]


In [ ]:
normalized = (grades - grades.min()) / (grades.max() - grades.min())
print(normalized)

[[0.75471698 0.8490566  0.62264151 0.88679245 0.81132075]
 [0.47169811 0.56603774 0.50943396 0.43396226 0.54716981]
 [0.94339623 1.         0.88679245 0.96226415 0.98113208]
 [0.28301887 0.37735849 0.24528302 0.32075472 0.26415094]
 [0.81132075 0.69811321 0.86792453 0.75471698 0.79245283]
 [0.09433962 0.18867925 0.         0.28301887 0.13207547]]


In [80]:
for i, x in enumerate(student_avg):
    if x >= 90:
        l_grade = "A+"
    elif x >= 80:
        l_grade = "A"
    elif x >= 70:
        l_grade = "B"
    elif x >= 60:
        l_grade = "C"
    elif x >= 50:
        l_grade = "D"
    else:
        l_grade = "F"
        
    print(f"Student: {i+ 1},\n Name: {name[i]},\n Grades: {grades[i]},\n letter Grade: {l_grade},\n Normalized: {normalized[i]},\n Average: {student_avg[i]},\n Standard Deviation: {stand_div[i]}\n")

Student: 1,
 Name: Abdullah,
 Grades: [85 90 78 92 88],
 letter Grade: A,
 Normalized: [0.75471698 0.8490566  0.62264151 0.88679245 0.81132075],
 Average: 86.6,
 Standard Deviation: 4.882622246293481

Student: 2,
 Name: Hossam,
 Grades: [70 75 72 68 74],
 letter Grade: B,
 Normalized: [0.47169811 0.56603774 0.50943396 0.43396226 0.54716981],
 Average: 71.8,
 Standard Deviation: 2.5612496949731396

Student: 3,
 Name: Ramadan,
 Grades: [95 98 92 96 97],
 letter Grade: A+,
 Normalized: [0.94339623 1.         0.88679245 0.96226415 0.98113208],
 Average: 95.6,
 Standard Deviation: 2.0591260281974

Student: 4,
 Name: Amin,
 Grades: [60 65 58 62 59],
 letter Grade: C,
 Normalized: [0.28301887 0.37735849 0.24528302 0.32075472 0.26415094],
 Average: 60.8,
 Standard Deviation: 2.4819347291981715

Student: 5,
 Name: Ibrahim,
 Grades: [88 82 91 85 87],
 letter Grade: A,
 Normalized: [0.81132075 0.69811321 0.86792453 0.75471698 0.79245283],
 Average: 86.6,
 Standard Deviation: 3.0066592756745814

S